# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 15:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('image_url', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_order', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamesrv.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('last_turn_date', models.DateTimeField(auto_now=True)),
                ('finished', models.BooleanField()),
                ('turn_number', models.IntegerField(default=1)),
                ('next_to_move', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_to_move', to=settings.AUTH_USER_MODEL)),
                ('player_1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_palyer_one', to=settings.AUTH_USER_MODEL)),
                ('player_2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_palyer_two', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='draft',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamesrv.Game'),
        ),
        migrations.AddField(
            model_name='card',
            name='seed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_of_the_card', to='gamesrv.Seed'),
        ),
    ]
