# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 14:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamesrv', '0004_game_deck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('H', 'Hand'), ('T', 'Table'), ('B', 'Blocked'), ('D', 'Discarded')], default='H', max_length=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamesrv.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, help_text='Adding a friendly message is never a bad idea!', max_length=300, verbose_name='Optional Message')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(help_text='Please select the user you want to play a game with', on_delete=django.db.models.deletion.CASCADE, related_name='invitations_received', to=settings.AUTH_USER_MODEL, verbose_name='User to invite')),
            ],
        ),
        migrations.RenameField(
            model_name='game',
            old_name='next_to_move',
            new_name='current_player',
        ),
        migrations.AddField(
            model_name='game',
            name='deck_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hand',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamesrv.Game'),
        ),
        migrations.AddField(
            model_name='hand',
            name='player',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_hand', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='players_hand',
            field=models.ManyToManyField(related_name='players_hand', through='gamesrv.Hand', to='gamesrv.Card'),
        ),
    ]
