# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamesrv', '0005_auto_20170517_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
