# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesrv', '0006_auto_20170526_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draft',
            options={'ordering': ['draft_order']},
        ),
        migrations.AlterField(
            model_name='game',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
